version: "3.7"

services:
  resource:
    build:
     context: .
     dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongo
    volumes: 
      - mongodb-data:/data/db
    ports:
      - 27017:27017

volumes: 
  mongodb-data:
