
//getting all users
GET http://localhost:3000/auth
###
// creating a user 
POST  http://localhost:3000/auth/register
content-type: application/json

{
    "userName": "rediane",
    "password": "123" 
}


